name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking Changes"
    when:
      labels:
        - "major"
  - title: "🚀 Features"
    when:
      labels:
        - "feature"
        - "enhancement"
  - title: "🐛 Bug Fixes"
    when:
      labels:
        - "fix"
        - "bugfix"
        - "bug"
  - title: "🧹 Maintenance"
    when:
      labels:
        - "chore"
        - "dependencies"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - "major"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - "feature"
        - "enhancement"
        - "minor"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - "fix"
        - "bugfix"
        - "bug"
        - "chore"
        - "dependencies"
        - "patch"
version-resolver:
  default: patch
template: |
  ## Changes

  $CHANGES
