name: 'Hello World'
description: 'Greet someone'
inputs:
  registry:
    description: 'Docker Registry'
    required: true
  username:
    description: 'Username for the Docker Registry'
    required: true
  password:
    description: 'Password for the Docker Registry'
    required: true
  dockerfile:
    description: 'Dockerfile'
    required: true
    default: './Dockerfile'
runs:
  using: "composite"
  steps:
    - name: Generate Tags
      id: preparation
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]] || [[ $GITHUB_REF == refs/heads/main ]]; then
          TAGS="${DOCKER_IMAGE}:master-${GITHUB_SHA::8},${DOCKER_IMAGE}:latest"
          PUSH="true"
        elif [[ $GITHUB_REF == refs/heads/dev ]]; then
          TAGS="${DOCKER_IMAGE}:dev-${GITHUB_SHA::8}"
          PUSH="true"
        else
          TAGS="${DOCKER_IMAGE}:${GITHUB_SHA::8}"
          PUSH="false"
        fi
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=push::${PUSH}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to the Docker Registry
      if: ${{ steps.preparation.outputs.push == 'true' }}
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ steps.preparation.outputs.push }}
        tags: ${{ steps.preparation.outputs.tags }}
