name: 'Hello World'
description: 'Greet someone'
inputs:
  dockerregistry:
    description: 'Docker Registry'
    required: true
    default: 'registry.staffbase.com'
  dockerimage:
    description: 'Docker Image'
    required: true
  dockerusername:
    description: 'Username for the Docker Registry'
    required: true
  dockerpassword:
    description: 'Password for the Docker Registry'
    required: true
  dockerfile:
    description: 'Dockerfile'
    required: true
    default: './Dockerfile'
runs:
  using: "composite"
  steps:
    - name: Generate Tags
      id: preparation
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]] || [[ $GITHUB_REF == refs/heads/main ]]; then
          TAGS="master-${GITHUB_SHA::8}"
          PUSH="true"
        elif [[ $GITHUB_REF == refs/heads/dev ]]; then
          TAGS="dev-${GITHUB_SHA::8}"
          PUSH="true"
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          TAGS="${GITHUB_REF:10}"
          PUSH="true"
        else
          TAGS="${GITHUB_SHA::8}"
          PUSH="false"
        fi

        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=push::${PUSH}

    - name: Build and Push the Docker Image
      shell: bash
      run: |
        docker login "${{ inputs.dockerregistry }}" -u "${{ inputs.dockerusername }}" --password-stdin <<< "${{ inputs.dockerpassword }}"

        docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.dockerregistry }}/${{ inputs.dockerimage }}:${{ steps.preparation.outputs.tags }} .

        if [[ ${{ steps.preparation.outputs.push }} == "true" ]]; then
          docker push ${{ inputs.dockerregistry }}/${{ inputs.dockerimage }}:${{ steps.preparation.outputs.tags }}
        fi
