name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@9ea5ca06a1ef865b0af9745b47ea74b731b65fc5 # v13.4.1
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
