name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@6e6c062d84ba4422de03d07b019b75c345f3606e # v17.1.0
    secrets:
      client_id: ${{ vars.STAFFBASE_ACTIONS_CLIENT_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
