name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@963c984dde02b0a8711f0d098aa9f8a7f2e50bca # v12.0.1
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
